/**
 * Real estate manager api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AgentsPost201Response { 
    id?: number;
    name?: string;
    email?: string;
    phone?: string;
    avatar?: string;
}

