/**
 * Real estate manager api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CitiesGet200ResponseInnerRegion } from './citiesGet200ResponseInnerRegion';


export interface CitiesGet200ResponseInner { 
    id?: number;
    name?: string;
    region_id?: number;
    region?: CitiesGet200ResponseInnerRegion;
}

