/**
 * Real estate manager api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RealEstatesIdGet200ResponseAgent } from './realEstatesIdGet200ResponseAgent';
import { RealEstatesGet200ResponseInnerCity } from './realEstatesGet200ResponseInnerCity';


export interface RealEstatesIdGet200Response { 
    id?: number;
    address?: string;
    zip_code?: string;
    price?: number;
    area?: number;
    bedrooms?: number;
    is_rental?: number;
    city_id?: number;
    description?: string;
    created_at?: string;
    city?: RealEstatesGet200ResponseInnerCity;
    agent_id?: number;
    agent?: RealEstatesIdGet200ResponseAgent;
}

