/**
 * Real estate manager api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RealEstatesGet200ResponseInnerCity } from './realEstatesGet200ResponseInnerCity';


export interface RealEstatesGet200ResponseInner { 
    id?: number;
    address?: string;
    zip_code?: string;
    price?: number;
    area?: number;
    bedrooms?: number;
    is_rental?: number;
    image?: string;
    city_id?: number;
    city?: RealEstatesGet200ResponseInnerCity;
}

