/**
 * Real estate manager api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RealEstatesPost201Response { 
    price?: string;
    zip_code?: string;
    description?: string;
    area?: string;
    city_id?: string;
    address?: string;
    agent_id?: string;
    bedrooms?: string;
    is_rental?: string;
    image?: string;
    created_at?: string;
    id?: number;
}

