/**
 * Real estate manager api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RealEstatesGet200ResponseInnerCityRegion } from './realEstatesGet200ResponseInnerCityRegion';


export interface RealEstatesGet200ResponseInnerCity { 
    id?: number;
    name?: string;
    region_id?: number;
    region?: RealEstatesGet200ResponseInnerCityRegion;
}

